SHOW DATABASES;

USE deathnote;

SHOW TABLES;

CREATE TABLE DANCE

INSERT INTO DANCE VALUES (1,'ARNOLD'),(2,'BOB'),(3,'CAT'),(4,'DOG');

SELECT * FROM DANCE;

CREATE TABLE MUSIC
    (ID INT,NAME VARCHAR(10));

INSERT INTO MUSIC VALUES (3,'DOG'),(4,'CAT'),(5,'LION'),(6,'BEAR');

SELECT * FROM MUSIC;

SHOW TABLES;

-- INNER JOIN ON ID
SELECT DANCE.ID,DANCE.NAME,MUSIC.ID,MUSIC.NAME
FROM DANCE
JOIN
MUSIC
ON DANCE.ID = MUSIC.ID

-- INNER JOIN ON NAME
SELECT DANCE.ID,DANCE.NAME,MUSIC.ID,MUSIC.NAME
FROM DANCE
JOIN
MUSIC
ON DANCE.NAME = MUSIC.NAME;

-- INNER JOIN ON 2 COLUMNS
SELECT DANCE.ID,DANCE.NAME,MUSIC.ID,MUSIC.NAME
FROM DANCE
JOIN
MUSIC
ON DANCE.NAME = MUSIC.NAME AND DANCE.ID = MUSIC.ID;

INSERT INTO DANCE
    VALUES(3,'DOG');
ALTER TABLE DANCE CHANGE COLUMN NAME HOTNAME VARCHAR(10);
-- INNER JOIN ON HOTNAME=NAME
SELECT DANCE.ID,DANCE.HOTNAME,MUSIC.ID,MUSIC.NAME
FROM DANCE
JOIN
MUSIC
ON DANCE.HOTNAME = MUSIC.NAME;

DELETE FROM DANCE WHERE HOTNAME='DOG' AND ID=3;

-- LEFT JOIN ON HOTNAME=NAME
-- DANCE IS APPEARING FIRST, SO DANCE IS THE LEFT TABLE
SELECT DANCE.ID,DANCE.HOTNAME,MUSIC.ID,MUSIC.NAME
FROM DANCE
LEFT JOIN
MUSIC
ON DANCE.HOTNAME = MUSIC.NAME;

-- RIGHT JOIN ON HOTNAME=NAME
-- MUSIC IS THE RIGHT TABLE BECAUSE IT IS APPEARING LATER
SELECT DANCE.ID,DANCE.HOTNAME,MUSIC.ID,MUSIC.NAME
FROM DANCE
RIGHT JOIN
MUSIC
ON DANCE.HOTNAME = MUSIC.NAME;

UPDATE DANCE SET HOTNAME='DOGGY' WHERE HOTNAME='DOG';
UPDATE DANCE SET HOTNAME='CATTY' WHERE HOTNAME='CAT';

SELECT DANCE.ID,DANCE.HOTNAME,MUSIC.ID,MUSIC.NAME
FROM DANCE
RIGHT JOIN
MUSIC
ON DANCE.HOTNAME = MUSIC.NAME;

-- CONSTRAINTS
CREATE TABLE NETFLIX
(SNO INT UNIQUE,
 MOVIE_NAME VARCHAR(10) NOT NULL,
 WATCHED BOOLEAN DEFAULT FALSE);

DESC NETFLIX;

INSERT INTO NETFLIX VALUES
    (1,'INTERSTELLAR',1),
    (2,'BEAUTIFULL MIND',1),
    (3,'DALAL STREET',0);

SELECT * FROM NETFLIX;

-- CONSTRAINTS TESTS
INSERT INTO NETFLIX VALUES
    (1,'365 DAYS',0);

INSERT INTO NETFLIX VALUES (4,NULL,1);

-- PRIMARY KEYS AND FOREIGN KEYS
USE classicmodels;

SHOW TABLES;

DESC customers;

SELECT customerNumber,customerName,city FROM customers;

DESC orders;

SELECT orderNumber,orderDate,status,CustomerNumber FROM orders;


